name: CI - Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.2
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linter
      run: pnpm run lint
      
    - name: Run tests
      run: pnpm run test:ci

  build-and-validate:
    name: Build & Validate Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.2
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build package
      run: pnpm run build
      
    - name: Validate built nodes
      run: |
        echo "Checking if nodes were built successfully..."
        if [ -f "dist/nodes/MongoDbMongoose/MongoDbMongoose.node.js" ]; then
          echo "✅ MongoDbMongoose node build successful"
        else
          echo "❌ MongoDbMongoose node build failed"
          exit 1
        fi
        
        if [ -f "dist/nodes/MongoDbChangeStream/MongoDbChangeStream.node.js" ]; then
          echo "✅ MongoDbChangeStream node build successful"
        else
          echo "❌ MongoDbChangeStream node build failed"
          exit 1
        fi
        
    - name: Check package size
      run: |
        echo "Creating package tarball to check size..."
        TARBALL=$(pnpm pack)
        if [ -f "$TARBALL" ]; then
          echo "✅ Package created: $TARBALL"
          echo "📦 Package size: $(ls -lh $TARBALL | awk '{print $5}')"
          echo "📁 Package contents (first 20 files):"
          tar -tzf "$TARBALL" | head -20
          echo "📊 Total files in package: $(tar -tzf $TARBALL | wc -l)"
          echo "🗑️ Cleaning up tarball..."
          rm -f "$TARBALL"
        else
          echo "❌ Failed to create package"
          exit 1
        fi
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.6.2
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run security audit
      run: pnpm audit --audit-level high
